### ISSUE TITLE
FIPS 140-2 Kernel Mode

### ISSUE THREAD

**Issue by david-paige-ctr** [RedHatGov/ssg-el7-kickstart#53]
In the FIPS 140-2 Kernel Mode, you set the boot partition by identifying it with "df /boot".  This provides the device name for the boot device.  However, since one of the best practices (at least according to the DISA STIG) is to use boot=UUID=xxxxxx to make it device independent.

Would it be better to use the UUID taken from blkid?

**Comment by jmaughmer** [comment]
I had found that it was not enabling fips mode when I had it checked. Instead of digging into it I just added it to my post install script. I'm not using the UUID because I often use vmware templates of a built system.

**Comment by david-paige-ctr** [comment]
Thanks for the reply.  It would be easy enough to tailor for my site.

David Paige

-----Original Message-----

**Comment by jmaughmer** [comment]
I just looked into a new 7.4 deployment before my post-install script and it appears that the FIPS setting is now being applied properly. I had issues with it on 7.3.

**Comment by fcaviggia** [comment]
David, that is a valid point I'll take a look at what it would take to modify this tonight. It should just be a simple modification of this script... patches welcome in the mean time.

https://github.com/RedHatGov/ssg-el7-kickstart/blob/master/config/hardening/fips-kernel-mode.sh

**Comment by jmaughmer** [comment]
I was just looking into why FIPS was not getting enabled on my systems and found that the second sed statement is failing because ${BOOT} contains /'s. If you change this to use the UUID that should fix the issue. Or this is how I was setting it in my post-install script.

# enable fips in grub
BOOTPART=$(lsblk -f | grep "/boot" | grep -v efi | cut -d " " -f1 | cut -c3-6)
sed -i '/GRUB_CMDLINE_LINUX/c\GRUB_CMDLINE_LINUX="audit=1 crashkernel=auto rd.lvm.lv=vg1/lv_root rd.lvm.lv=vg1/lv_swap rhgb quiet rd.shell=0 boot=/dev/'"$BOOTPART"' fips=1"' /etc/default/grub
if [ -f "/boot/grub.conf" ]; then
  grub2-mkconfig -o /boot/grub2/grub.cfg
elif [ -f "/boot/efi/EFI/redhat/grub.cfg" ]; then
  grub2-mkconfig -o /boot/efi/EFI/redhat/grub.cfg
fi

**Comment by fcaviggia** [comment]
Here's my proposed solution:

https://github.com/RedHatGov/ssg-el7-kickstart/commit/251e39e5f5639dbdd98e58dec0fc1dd943a00ff2

**Comment by ajd394** [comment]
@fcaviggia can we close this?

**Comment by fcaviggia** [comment]
Yeah, looks like I did the updates to the FIPS 140-2 script.
